export {
  checkDraft,
  type ReviewResult,
  ownershipVolatilityGate,
  coPetitionerFundCircularityGate,
  unaccountedSofShareGate,
  multiRoundRfeEscalationGate,
  b2StatusViolationSignalGate,
  statusGapPreFilingGate,
  materialChangeInResponseToUscisGate,
  materialChangeInResponseToUscisGateAsync,
  MATERIAL_CHANGE_COMPARATOR_THRESHOLD,
  externalEvidenceContradictionRiskGate,
  developAndDirectRoleAuthorityThinGate,
  fiveYearHorizonMarginalFailureGate,
  fiveYearHorizonVsBusinessPlanDriftGate,
  FIVE_YEAR_HORIZON_REVENUE_DRIFT_THRESHOLD,
  FIVE_YEAR_HORIZON_EMPLOYEE_DRIFT_THRESHOLD,
  E2_DETERMINISTIC_GATES,
  runE2DeterministicGates,
  runE2DeterministicGatesAsync,
  renderGateBlock,
  runFullReview,
  runFullReviewWithEmbeddingComparator,
  type GateOutcome,
  type GateName,
  type GateFn,
  type GateRunResult,
  type FullReviewResult,
  type RunFullReviewOptions,
  type ComparatorOption,
} from './checker';
export {
  createAssertionComparator,
  type AssertionComparator,
  type AssertionComparison,
} from './material-change-comparator';
export {
  embeddingMaterialChangeComparator,
  createEmbeddingAssertionComparator,
  EMBEDDING_COMPARATOR_DEFAULT_THRESHOLD,
  type EmbeddingComparatorOptions,
  type EmbeddingComparison,
  type EmbedFn,
} from './embedding-comparator';
export {
  ReviewReportSchema,
  type ReviewReport,
  type Inconsistency,
  type MissingArgument,
  type WeakSpot,
} from './schema';
