/**
 * EB-1A document structural-variant manifest (Tier-0 classifier corpus).
 *
 * Source-of-truth for the EB-1A variant cascade. Each entry is a single
 * generic structural variant from research/2026-05-05_eb1a-doc-variant-
 * taxonomy.md (17 doc_types · 41 variants).
 *
 * The classifier (eb1a-variant-classify.ts) consumes this manifest as
 * the structured artifact recommended by manuals/_EB1A-CROSS-REVIEW-v1.md
 * § 6 ("extract signals into a structured YAML/JSON manifest … not the
 * Markdown"). Markdown stays human-readable; this file is what the cascade
 * actually reads.
 *
 * Authority for the criterion vocabulary: 8 CFR § 204.5(h)(3)(i)–(x).
 * Maps from intake-taxonomy labels (Awards / Membership / Media / Judge /
 * Original Contributions / Authorship / Critical Role / Remuneration /
 * Display / Commercial Success) used internally by Atelier into the
 * regulatory roman-numeral form.
 *
 * IMPORTANT: do NOT edit this file by hand without re-reading the source
 * markdown. Adding a variant requires bumping
 * `EB1A_VARIANT_MANIFEST_VERSION` so the cascade can invalidate caches.
 */

/* eslint-disable @typescript-eslint/no-namespace */

/** (h)(3) regulatory roman-numeral identifier. */
export type Hh3Criterion =
  | 'h3_i'   // Awards
  | 'h3_ii'  // Membership
  | 'h3_iii' // Media
  | 'h3_iv'  // Judge
  | 'h3_v'   // Original Contributions
  | 'h3_vi'  // Authorship
  | 'h3_vii' // Display
  | 'h3_viii'// Critical Role
  | 'h3_ix'  // Remuneration
  | 'h3_x';  // Commercial Success

/**
 * EB-1A doc_type ids — these are the 17 structural-variant doc_types
 * from the EB-1A taxonomy. Distinct from the E-2 fine-grained
 * `lib/e2/doc-taxonomy` ids; the EB-1A classifier owns its own
 * vocabulary because the regulatory grammar is different.
 */
export type Eb1aDocType =
  | 'award_certificate'
  | 'recommendation_letter'
  | 'citation_report'
  | 'peer_review_invitation'
  | 'editorial_board_notice'
  | 'media_article'
  | 'published_paper'
  | 'conference_invitation'
  | 'judging_task_record'
  | 'patent_or_ip_filing'
  | 'salary_evidence'
  | 'membership_credential'
  | 'cv_or_resume'
  | 'exhibition_record'
  | 'commercial_success_record'
  | 'org_reputation_packet'
  | 'comparable_evidence_packet';

/**
 * Variant id is the doc_type id plus the 1-indexed variant slot, e.g.
 * "recommendation_letter:v1". Stable across releases; used as a key in
 * downstream gates.
 */
export type Eb1aVariantId = `${Eb1aDocType}:v${1 | 2 | 3 | 4}`;

export interface Eb1aVariant {
  doc_type: Eb1aDocType;
  variant_id: Eb1aVariantId;
  /** 1-line human label (matches the Markdown taxonomy). */
  label: string;
  /**
   * Which (h)(3) criteria this variant maps to. Multi-criterion variants
   * (e.g., expert letters) carry the full set; the criterion-gate consumer
   * decides which specific gate ingests this evidence.
   */
  criterion_map: Hh3Criterion[];
  /**
   * Filename keywords from the taxonomy. Folded (NFD-stripped, lowercased)
   * before matching. Each entry is a substring; the classifier scores any
   * hit as a positive filename signal.
   */
  filename_keywords: string[];
  /**
   * Content-text signals — regex patterns evaluated against the first-page
   * text. Each pattern that hits adds to the score. Patterns are crafted
   * from the taxonomy "Classifier signals" + "Distinguishing markers"
   * triples.
   */
  content_signals: RegExp[];
  /**
   * Negative signals: when present, this variant SHOULD NOT fire.
   * Encodes cross-review § 6 disambiguation rules
   * (predatory-venue red-flags, paper-vs-media references-section
   * exclusion, etc.). Each pattern that hits is logged and subtracts
   * weight from the variant; if a hard exclusion fires, the variant is
   * removed from candidate list entirely.
   */
  exclusion_signals: RegExp[];
  /**
   * Variants that frequently collide with this one. The classifier uses
   * this to apply tiebreakers; pairing is symmetric, listed once per
   * primary variant.
   */
  collides_with?: Eb1aVariantId[];
  /**
   * Cascade flag. `non_anchor` variants MUST NOT fire any criterion-
   * classifier branch on their own (e.g., cv_or_resume). They are
   * orienting documents for the human reviewer and the cross-doc gates.
   */
  cascade_flag?: 'non_anchor';
  /**
   * Hard-flag variants are surfaced as warnings on classification
   * (e.g., predatory-venue red-flag).
   */
  hard_flag?: 'predatory_venue_redflag';
}

export const EB1A_VARIANT_MANIFEST_VERSION = '2026-05-05.1';

/**
 * The 41 EB-1A structural variants. Order tracks the markdown taxonomy
 * for diff-friendliness; the classifier does not depend on order.
 */
export const EB1A_VARIANT_MANIFEST: readonly Eb1aVariant[] = [
  /* award_certificate (3) ------------------------------------------------ */
  {
    doc_type: 'award_certificate',
    variant_id: 'award_certificate:v1',
    label: 'Formal printed certificate / diploma',
    criterion_map: ['h3_i'],
    filename_keywords: [
      'award', 'certificate', 'diploma', 'prize', 'honor', 'odul', 'sertifika',
    ],
    content_signals: [
      /\bcertificate\s+of\s+(achievement|excellence|merit|recognition|award)\b/i,
      /\bis\s+hereby\s+(awarded|presented|conferred)\b/i,
      /\b(awarded|presented)\s+to\b[^.\n]{0,80}/i,
    ],
    exclusion_signals: [
      /\bpress\s+release\b/i,
      /\beligibility\s+criteria\b/i,
    ],
  },
  {
    doc_type: 'award_certificate',
    variant_id: 'award_certificate:v2',
    label: 'Award announcement / press release',
    criterion_map: ['h3_i'],
    filename_keywords: [
      'announcement', 'press-release', 'awardees', 'laureate', 'winners', 'duyuru',
    ],
    content_signals: [
      /\b(announces|named|selected|honored|recognized)\b[^.\n]{0,120}\b(winners?|laureate|recipient)/i,
      /\bjury\s+(panel|members)\b/i,
      /\b(class|cohort)\s+of\s+\d{4}\b/i,
    ],
    exclusion_signals: [/\bcurriculum\s+vitae\b/i],
  },
  {
    doc_type: 'award_certificate',
    variant_id: 'award_certificate:v3',
    label: 'Award-program rules / selection-criteria packet',
    criterion_map: ['h3_i'],
    filename_keywords: [
      'rules', 'criteria', 'eligibility', 'jury', 'about-the-prize',
    ],
    content_signals: [
      /\beligibility\b[^.\n]{0,80}/i,
      /\bselection\s+(criteria|process)\b/i,
      /\bjury\s+(composition|panel|members)\b/i,
    ],
    exclusion_signals: [/\bawarded\s+to\s+\b/i],
  },

  /* recommendation_letter (3) ------------------------------------------- */
  {
    doc_type: 'recommendation_letter',
    variant_id: 'recommendation_letter:v1',
    label: 'Independent expert opinion letter',
    // (h)(3) variant mapping per cross-review P1 #6: expert letters can
    // analyze ANY criterion the firm pleads.
    criterion_map: [
      'h3_i', 'h3_ii', 'h3_iii', 'h3_iv', 'h3_v', 'h3_vi', 'h3_viii',
    ],
    filename_keywords: [
      'expert', 'independent', 'opinion', 'ev-letter', 'recommendation', 'ref',
      'tavsiye',
    ],
    content_signals: [
      // Cross-review § 6 #1 — independence sentence.
      /\bI\s+have\s+(never|not)\s+(met|collaborated|worked|co[-\s]?authored)\b/i,
      /\bI\s+am\s+not\s+(affiliated|associated|connected)\b/i,
      /\bno\s+(prior|personal|professional)\s+(tie|relationship|connection)\b/i,
      // Letterhead-domain heuristic (institutional-domain != beneficiary's).
      /@(?:[a-z0-9-]+\.)+(?:edu|ac\.[a-z]{2}|org|gov)/i,
    ],
    // Hard exclusion for the dependent-letter language.
    exclusion_signals: [
      /\bI\s+(supervised|advised|co[-\s]?authored|employed|managed)\b[^.\n]{0,80}\bhim|her|them\b/i,
      /\bmy\s+(former|current)\s+(student|advisee|employee|colleague)\b/i,
    ],
    collides_with: ['recommendation_letter:v2'],
  },
  {
    doc_type: 'recommendation_letter',
    variant_id: 'recommendation_letter:v2',
    label: 'Dependent / collaborator letter',
    criterion_map: [
      'h3_i', 'h3_ii', 'h3_iii', 'h3_iv', 'h3_v', 'h3_vi', 'h3_viii',
    ],
    filename_keywords: [
      'collaborator', 'advisor', 'supervisor', 'coauthor', 'employer-letter',
    ],
    content_signals: [
      // Cross-review § 6 #1 — affirmative-tie sentence in opening.
      /\bI\s+(supervised|advised|co[-\s]?authored|employed|managed|mentored)\b/i,
      /\bmy\s+(former|current)\s+(student|advisee|employee|colleague|collaborator)\b/i,
      /\bwe\s+(co[-\s]?authored|jointly|collaborated)\b/i,
      /\bin\s+my\s+(lab|group|department|team)\b/i,
    ],
    exclusion_signals: [
      /\bI\s+have\s+(never|not)\s+(met|collaborated|worked)\b/i,
    ],
    collides_with: ['recommendation_letter:v1'],
  },
  {
    doc_type: 'recommendation_letter',
    variant_id: 'recommendation_letter:v3',
    label: 'Short endorsement / blurb',
    criterion_map: [
      'h3_i', 'h3_ii', 'h3_iii', 'h3_iv', 'h3_v', 'h3_vi', 'h3_viii',
    ],
    filename_keywords: ['endorsement', 'blurb', 'short-letter', 'note'],
    content_signals: [
      // Endorsement language without the 5-section structure. Scoring
      // happens at the classifier level via word-count heuristic in
      // eb1a-variant-classify.ts; these regexes catch the verb shape.
      /\b(I\s+(strongly\s+)?endorse|I\s+wholeheartedly\s+support|I\s+recommend)\b/i,
      /\bsincerely\s+yours\b/i,
    ],
    exclusion_signals: [
      // 5-section heading structure → not a blurb.
      /^\s*(Background|Field|Contribution|Significance|Conclusion)\s*[:\n]/im,
    ],
  },

  /* citation_report (3) ------------------------------------------------- */
  {
    doc_type: 'citation_report',
    variant_id: 'citation_report:v1',
    label: 'Database screenshot / export',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'scholar', 'scopus', 'wos', 'citations', 'h-index', 'profile', 'export',
    ],
    content_signals: [
      /\b(google\s+scholar|scopus|web\s+of\s+science|orcid)\b/i,
      /\bh[-\s]?index\b/i,
      /\bi10[-\s]?index\b/i,
      /\bcited\s+by\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'citation_report',
    variant_id: 'citation_report:v2',
    label: 'Citation analysis memo',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'citation-analysis', 'metrics-memo', 'impact-summary',
    ],
    content_signals: [
      /\btop\s+\d+\s*%\b/i,
      /\b(percentile|comparator|baseline)\b/i,
      /\b(citation|impact)\s+(analysis|summary)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'citation_report',
    variant_id: 'citation_report:v3',
    label: 'Field-normalized impact memo (FWCI / SciVal / InCites)',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'fwci', 'scival', 'incites', 'dimensions', 'field-weighted',
      'percentile', 'top-percent', 'normalized-impact',
    ],
    content_signals: [
      /\bFWCI\b/i,
      /\bfield[-\s]?weighted\s+citation\s+impact\b/i,
      /\b(SciVal|InCites|Dimensions)\b/,
      /\bASJC\b/,
      /\btop\s+\d+\s*%\s+in\s+field\b/i,
    ],
    exclusion_signals: [],
  },

  /* peer_review_invitation (2) ------------------------------------------ */
  {
    doc_type: 'peer_review_invitation',
    variant_id: 'peer_review_invitation:v1',
    label: 'Journal review request email',
    criterion_map: ['h3_iv'],
    filename_keywords: [
      'review-invite', 'peer-review', 'manuscript', 'editor',
    ],
    content_signals: [
      /\b(review\s+invitation|invitation\s+to\s+review|review\s+request)\b/i,
      /\bmanuscript\s+(id|number|reference)\b/i,
      /\b(agree\s+to\s+review|decline)\b/i,
      /\b(editor|associate\s+editor|editor[-\s]?in[-\s]?chief)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'peer_review_invitation',
    variant_id: 'peer_review_invitation:v2',
    label: 'Completed-review confirmation',
    criterion_map: ['h3_iv'],
    filename_keywords: [
      'review-completed', 'publons', 'reviewer-record',
    ],
    content_signals: [
      /\bthank\s+you\s+for\s+(completing|submitting|your)\s+(your\s+)?review\b/i,
      /\b(publons|reviewer\s+recognition|web\s+of\s+science\s+reviewer)\b/i,
      /\b(verified|completed)\s+reviews?\b/i,
    ],
    exclusion_signals: [],
  },

  /* editorial_board_notice (2) ----------------------------------------- */
  {
    doc_type: 'editorial_board_notice',
    variant_id: 'editorial_board_notice:v1',
    label: 'Appointment / invitation letter to editorial board / PC',
    criterion_map: ['h3_iv'],
    filename_keywords: [
      'editorial-board', 'appointment', 'invitation', 'program-committee',
    ],
    content_signals: [
      // Cross-review § 6 #2 — role-keyword whitelist for editor / PC.
      /\b(editor|associate\s+editor|board\s+member|program\s+committee|PC\s+member)\b/i,
      /\b(invite\s+to\s+serve|appointment\s+to\s+the)\b/i,
      /\b(term\s+(of|length)|two[-\s]?year\s+term|three[-\s]?year\s+term)\b/i,
    ],
    exclusion_signals: [
      // Cross-review § 6 #2 — explicit speaker/keynote/panelist words push
      // the doc to conference_invitation:v1 instead.
      /\b(keynote|invited\s+speaker|panelist|session\s+speaker)\b/i,
    ],
    collides_with: ['conference_invitation:v1'],
  },
  {
    doc_type: 'editorial_board_notice',
    variant_id: 'editorial_board_notice:v2',
    label: 'Masthead / board roster',
    criterion_map: ['h3_iv'],
    filename_keywords: [
      'masthead', 'board-roster', 'editors-page', 'committee-list',
    ],
    content_signals: [
      /\beditorial\s+board\b/i,
      /\bprogram\s+committee\b/i,
      /\b(editor|associate\s+editor|board\s+member)\b[^.\n]{0,40}\baffiliations?\b/i,
    ],
    exclusion_signals: [],
  },

  /* media_article (3) -------------------------------------------------- */
  {
    doc_type: 'media_article',
    variant_id: 'media_article:v1',
    label: 'Feature / profile article about beneficiary',
    criterion_map: ['h3_iii'],
    filename_keywords: [
      'profile', 'feature', 'article', 'press', 'media',
    ],
    content_signals: [
      /\bby\s+[A-Z][a-z]+\s+[A-Z][a-z]+/, // byline pattern
      /\b(reuters|associated\s+press|new\s+york\s+times|wall\s+street\s+journal|bloomberg|wired|forbes|the\s+economist)\b/i,
      /\bphoto:\s+/i,
    ],
    // Cross-review § 6 #3: media articles SHOULD lack a journal references
    // section. If a references list is present, the doc is more likely a
    // published_paper:v1 — exclude.
    exclusion_signals: [
      /\b(References|Bibliography|Literature\s+Cited)\s*\n/i,
      /\bdoi\.org\/10\.\d{4,9}\b/i,
    ],
    collides_with: ['published_paper:v1'],
  },
  {
    doc_type: 'media_article',
    variant_id: 'media_article:v2',
    label: 'Interview / Q&A',
    criterion_map: ['h3_iii'],
    filename_keywords: [
      'interview', 'qa', 'q-a', 'conversation', 'roportaj',
    ],
    content_signals: [
      /\bQ:\s+/m,
      /\bA:\s+/m,
      /\binterview\s+with\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'media_article',
    variant_id: 'media_article:v3',
    label: 'Circulation / reach evidence',
    criterion_map: ['h3_iii'],
    filename_keywords: [
      'circulation', 'audience', 'reach', 'media-kit', 'ranking',
    ],
    content_signals: [
      /\b(unique\s+visitors|monthly\s+readers|print\s+run|circulation)\b/i,
      /\bmedia\s+kit\b/i,
      /\baudience\s+(size|profile|reach)\b/i,
    ],
    exclusion_signals: [],
  },

  /* published_paper (4) ------------------------------------------------ */
  {
    doc_type: 'published_paper',
    variant_id: 'published_paper:v1',
    label: 'Peer-reviewed journal article (PDF reprint)',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'paper', 'journal', 'article', 'doi', 'reprint',
    ],
    content_signals: [
      // Cross-review § 6 #3 — DOI is the strong positive; references-
      // section presence is the disambiguation against media_article:v1.
      /\b10\.\d{4,9}\/[-._;()/:A-Z0-9]+/i,
      /\bAbstract\b\s*\n/,
      /\b(Volume|Vol\.)\s*\d+/i,
      /\b(References|Bibliography)\s*\n/,
      /\bORCID\b/i,
    ],
    exclusion_signals: [],
    collides_with: ['media_article:v1'],
  },
  {
    doc_type: 'published_paper',
    variant_id: 'published_paper:v2',
    label: 'Conference proceedings paper',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'proceedings', 'conference', 'lncs', 'ieee-conf', 'acm',
    ],
    content_signals: [
      /\b(IEEE|ACM|Springer|LNCS|Elsevier)\b\s+[A-Z]/, // publisher banner
      /\bproceedings\s+of\s+the\b/i,
      /\bISBN[\s:]+(?:97[89][-\s]?)?\d/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'published_paper',
    variant_id: 'published_paper:v3',
    label: 'Book chapter / edited-volume contribution',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'chapter', 'book', 'edited-volume', 'springer', 'routledge',
    ],
    content_signals: [
      /\bChapter\s+\d+\b/,
      /\bedited\s+by\b/i,
      /\bISBN[\s:]+(?:97[89][-\s]?)?\d/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'published_paper',
    variant_id: 'published_paper:v4',
    label: 'Predatory-venue red-flag pattern',
    criterion_map: ['h3_v', 'h3_vi'],
    filename_keywords: [
      'oa-pay', 'fast-track', 'omics', 'beall', 'predatory-flag',
    ],
    content_signals: [
      /\bfast[-\s]?track\s+(review|publication)\b/i,
      /\brapid\s+(review|publication)\b/i,
      /\bpay\s+to\s+publish\b/i,
      /\barticle\s+processing\s+charge\b[^.\n]{0,80}\b\$\d/i,
      /\bsubmission\s+to\s+publication[^.\n]{0,40}\b(\d+\s+days|under\s+\d+\s+days)\b/i,
    ],
    exclusion_signals: [],
    hard_flag: 'predatory_venue_redflag',
  },

  /* conference_invitation (2) ------------------------------------------ */
  {
    doc_type: 'conference_invitation',
    variant_id: 'conference_invitation:v1',
    label: 'Speaker / keynote invitation letter',
    // Cross-review P1 #7: keynote/invited-speaker → (v) Original
    // Contributions; session-chair/PC role lives in editorial_board_notice
    // / judging_task_record. We keep the (h)(3)(v) anchor here.
    criterion_map: ['h3_v'],
    filename_keywords: [
      'keynote', 'invited-speaker', 'panelist', 'conference-invite',
    ],
    content_signals: [
      // Cross-review § 6 #2 — role-keyword whitelist for speaker side.
      /\b(keynote\s+speaker|invited\s+speaker|plenary\s+speaker|panelist)\b/i,
      /\b(invite\s+(you\s+)?to\s+(deliver|present|speak|give))\b/i,
      /\b(honorarium|travel\s+(stipend|reimbursement))\b/i,
      /\bprogram\s+chair\b/i,
    ],
    exclusion_signals: [
      // Editor / board-member words push to editorial_board_notice:v1.
      /\b(editor|associate\s+editor|board\s+member|program\s+committee\s+member|PC\s+member)\b/i,
    ],
    collides_with: ['editorial_board_notice:v1'],
  },
  {
    doc_type: 'conference_invitation',
    variant_id: 'conference_invitation:v2',
    label: 'Conference program / agenda',
    criterion_map: ['h3_v'],
    filename_keywords: [
      'program', 'agenda', 'schedule', 'sessions', 'speakers-list',
    ],
    content_signals: [
      /\b\d{1,2}:\d{2}\s*(AM|PM)?\b[^.\n]{0,40}\b(session|panel|keynote|talk)\b/i,
      /\b(speakers?|panelists?)\s*[:\n]/i,
      /\bagenda\b/i,
    ],
    exclusion_signals: [],
  },

  /* judging_task_record (2) -------------------------------------------- */
  {
    doc_type: 'judging_task_record',
    variant_id: 'judging_task_record:v1',
    label: 'Judging assignment / rubric package',
    criterion_map: ['h3_iv'],
    filename_keywords: [
      'judge', 'jury', 'evaluator', 'rubric', 'grant-panel', 'thesis-jury',
    ],
    content_signals: [
      /\b(appointed|assigned|invited)\s+(as|to\s+(serve|act))\s+(a\s+)?(judge|juror|evaluator)\b/i,
      /\bscoring\s+(rubric|criteria|sheet)\b/i,
      /\bconfidentiality\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'judging_task_record',
    variant_id: 'judging_task_record:v2',
    label: 'Completed-judging confirmation',
    criterion_map: ['h3_iv'],
    filename_keywords: [
      'judging-confirmation', 'thank-you-judge', 'jury-completed',
    ],
    content_signals: [
      /\b(thank\s+you\s+for\s+serving|served\s+as\s+(a\s+)?(judge|juror|evaluator))\b/i,
      /\bcompleted\s+(your|the)\s+(judging|evaluation)\b/i,
      /\b(cycle|cohort|year)\s+\d{4}\b/,
    ],
    exclusion_signals: [],
  },

  /* patent_or_ip_filing (3) -------------------------------------------- */
  {
    doc_type: 'patent_or_ip_filing',
    variant_id: 'patent_or_ip_filing:v1',
    label: 'Granted patent face / front page',
    criterion_map: ['h3_v'],
    filename_keywords: [
      'patent', 'granted', 'uspto', 'epo', 'wipo', 'turkpatent',
    ],
    content_signals: [
      /\bUS\s*\d{7,8}\s*B\d?\b/,
      /\bEP\s*\d{7}\s*B\d\b/,
      /\b(USPTO|EPO|WIPO|T[ÜU]RKPATENT)\b/i,
      /\b(Inventor|Inventors|Assignee)\s*[:\n]/i,
      /\b(Filed|Filing\s+Date|Granted|Date\s+of\s+Patent)\b/i,
    ],
    exclusion_signals: [
      /\b(Pub(\.|lication)\s+Date|Application\s+Number)\b/i,
    ],
  },
  {
    doc_type: 'patent_or_ip_filing',
    variant_id: 'patent_or_ip_filing:v2',
    label: 'Pending application / publication',
    criterion_map: ['h3_v'],
    filename_keywords: [
      'application', 'pending', 'published-app', 'pre-grant',
    ],
    content_signals: [
      /\bUS\s*\d{4}\/\d{7}\s*A\d?\b/,
      /\bPub(\.|lication)\s+(No\.?|Date)\b/i,
      /\bApplication\s+(Number|No\.)\b/i,
    ],
    exclusion_signals: [
      /\b(Date\s+of\s+Patent|Granted)\b/i,
    ],
  },
  {
    doc_type: 'patent_or_ip_filing',
    variant_id: 'patent_or_ip_filing:v3',
    label: 'Citation / forward-citation evidence',
    criterion_map: ['h3_v'],
    filename_keywords: [
      'forward-citations', 'cited-by', 'lens', 'google-patents',
    ],
    content_signals: [
      /\b(Google\s+Patents|Lens\.org|USPTO\s+PAIR)\b/i,
      /\bcited\s+by\b[^.\n]{0,40}\b(\d+\s+(patents?|papers?))\b/i,
      /\bforward\s+citations?\b/i,
    ],
    exclusion_signals: [],
  },

  /* salary_evidence (3) ------------------------------------------------ */
  {
    doc_type: 'salary_evidence',
    variant_id: 'salary_evidence:v1',
    label: 'Pay record (W-2 / paystub / 1099 / payroll)',
    criterion_map: ['h3_ix'],
    filename_keywords: [
      'w2', 'w-2', 'paystub', '1099', 'payroll', 'salary', 'bordro',
    ],
    content_signals: [
      /\bForm\s+W[-\s]?2\b/i,
      /\bForm\s+1099[-\s]?(NEC|MISC)\b/i,
      /\b(Pay\s+Statement|Pay\s+Period|Earnings\s+Statement)\b/i,
      /\bGross\s+(Pay|Wages)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'salary_evidence',
    variant_id: 'salary_evidence:v2',
    label: 'Employment contract / offer letter (compensation clause)',
    criterion_map: ['h3_ix'],
    filename_keywords: [
      'offer', 'contract', 'employment-agreement', 'compensation-clause',
    ],
    content_signals: [
      /\b(Offer\s+Letter|Employment\s+Agreement)\b/i,
      /\b(annual\s+(base\s+)?salary|base\s+compensation|sign[-\s]?on\s+bonus)\b/i,
      /\b(equity|RSUs?|stock\s+options?)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'salary_evidence',
    variant_id: 'salary_evidence:v3',
    label: 'Comparable-salary benchmark report (US + EU/TR)',
    criterion_map: ['h3_ix'],
    filename_keywords: [
      'bls', 'oews', 'oflc', 'mercer', 'radford', 'payscale', 'glassdoor',
      'salary-survey', 'tuik', 'eurostat', 'ses', 'robert-half-emea',
    ],
    content_signals: [
      /\b(BLS|OEWS|OFLC|Mercer|Radford|Payscale|Glassdoor)\b/i,
      /\b(T[ÜU][İI]K|Eurostat|Robert\s+Half(\s+EMEA)?)\b/i,
      /\b(10th|50th|90th)\s+percentile\b/i,
      /\bSOC\s+(code|\d{2}-\d{4})\b/i,
      /\b(NACE|ISCO|NUTS)\b/,
    ],
    exclusion_signals: [],
  },

  /* membership_credential (2) ------------------------------------------ */
  {
    doc_type: 'membership_credential',
    variant_id: 'membership_credential:v1',
    label: 'Admission / induction letter',
    criterion_map: ['h3_ii'],
    filename_keywords: [
      'admission', 'induction', 'election', 'fellow', 'member-letter',
    ],
    content_signals: [
      /\b(elected|inducted|admitted)\s+(as|to|into)\b/i,
      /\b(Fellow|Member|Academician)\s+of\s+the\b/i,
      /\bwe\s+are\s+pleased\s+to\s+inform\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'membership_credential',
    variant_id: 'membership_credential:v2',
    label: 'Membership-criteria / bylaws excerpt',
    criterion_map: ['h3_ii'],
    filename_keywords: [
      'criteria', 'bylaws', 'fellowship-rules', 'eligibility', 'how-to-join',
    ],
    content_signals: [
      /\b(eligibility|selection\s+criteria|fellowship\s+criteria)\b/i,
      /\bbylaws\b/i,
      /\bpeer\s+nomination\b/i,
    ],
    exclusion_signals: [],
  },

  /* cv_or_resume (2) — non-anchor -------------------------------------- */
  {
    doc_type: 'cv_or_resume',
    variant_id: 'cv_or_resume:v1',
    label: 'Academic CV (long-form, EB-1A flavored)',
    // Cross-cutting per taxonomy; the cascade flag enforces no
    // criterion-classifier branch fires off the CV alone.
    criterion_map: [],
    filename_keywords: [
      'cv', 'curriculum-vitae', 'academic-cv', 'long-cv', 'ozgecmis',
    ],
    content_signals: [
      /\bCurriculum\s+Vit(ae|a)\b/i,
      /\b(Publications?|Selected\s+Publications)\b/,
      /\b(Awards?|Honors?)\b/,
      /\b(Talks?|Invited\s+Lectures?|Keynotes?)\b/,
    ],
    exclusion_signals: [],
    cascade_flag: 'non_anchor',
  },
  {
    doc_type: 'cv_or_resume',
    variant_id: 'cv_or_resume:v2',
    label: 'Industry resume (short-form)',
    criterion_map: [],
    filename_keywords: [
      'resume', 'cv-short', 'one-pager', 'ozgecmis',
    ],
    content_signals: [
      /\b(Skills|Tools|Technologies)\s*[:\n]/i,
      /\b(Education|Experience)\s*[:\n]/i,
    ],
    exclusion_signals: [],
    cascade_flag: 'non_anchor',
  },

  /* exhibition_record (3) ---------------------------------------------- */
  {
    doc_type: 'exhibition_record',
    variant_id: 'exhibition_record:v1',
    label: 'Exhibition catalog / curator statement',
    criterion_map: ['h3_vii'],
    filename_keywords: [
      'catalog', 'catalogue', 'curator-statement', 'exhibition-essay',
      'sergi-katalog',
    ],
    content_signals: [
      /\b(Curator(?:ial)?\s+(Statement|Note|Essay))\b/i,
      /\bexhibition\s+(catalog|catalogue)\b/i,
      /\b(medium|year|dimensions)\s*[:\n]/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'exhibition_record',
    variant_id: 'exhibition_record:v2',
    label: 'Venue-reputation packet',
    criterion_map: ['h3_vii'],
    filename_keywords: [
      'venue', 'museum-about', 'gallery-profile', 'biennale', 'sergi-mekan',
    ],
    content_signals: [
      /\b(About|Our\s+Program|Collection|Permanent\s+Collection)\b/i,
      /\b(prior|past)\s+(exhibitions?|exhibitors?|artists)\b/i,
      /\b(AAM|ICOM|biennale)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'exhibition_record',
    variant_id: 'exhibition_record:v3',
    label: 'Exhibition press / review coverage',
    criterion_map: ['h3_vii'],
    filename_keywords: [
      'review', 'exhibition-press', 'art-review', 'sergi-elestirisi',
    ],
    content_signals: [
      /\b(this\s+)?(exhibition|show)\b[^.\n]{0,80}\b(opens|runs|on\s+view)\b/i,
      /\b(reviewed\s+by|critic|art\s+critic)\b/i,
    ],
    exclusion_signals: [],
  },

  /* commercial_success_record (2) -------------------------------------- */
  {
    doc_type: 'commercial_success_record',
    variant_id: 'commercial_success_record:v1',
    label: 'Audited sales / box-office / streaming report',
    criterion_map: ['h3_x'],
    filename_keywords: [
      'box-office', 'sales-report', 'audited', 'streaming-report', 'riaa',
      'luminate', 'gise',
    ],
    content_signals: [
      /\b(Box\s+Office\s+Mojo|RIAA|IFPI|Luminate|MRC)\b/i,
      /\b(units|revenue|streams|tickets)\s+sold\b/i,
      /\b(opening\s+weekend|domestic\s+gross|worldwide\s+gross)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'commercial_success_record',
    variant_id: 'commercial_success_record:v2',
    label: 'Chart-position evidence',
    criterion_map: ['h3_x'],
    filename_keywords: [
      'chart', 'billboard', 'ifpi', 'muyap', 'top-100', 'chart-position',
    ],
    content_signals: [
      /\b(Billboard|IFPI|M[ÜU][-\s]?YAP)\b/i,
      /\b(#\d+|No\.\s*\d+|rank\s+\d+)\b/i,
      /\b(top\s+(10|40|100|200))\b/i,
    ],
    exclusion_signals: [],
  },

  /* org_reputation_packet (3) ------------------------------------------ */
  {
    doc_type: 'org_reputation_packet',
    variant_id: 'org_reputation_packet:v1',
    label: 'Rankings / awards-to-organization',
    criterion_map: ['h3_viii'],
    filename_keywords: [
      'ranking', 'league-table', 'top-firms', 'award-to-org', 'kurumsal-odul',
    ],
    content_signals: [
      /\b(Forbes|Financial\s+Times|FT|Fortune\s+\d+)\b/i,
      /\b(top\s+\d+|league\s+table|ranking|ranked\s+\#?\d+)\b/i,
      /\bmethodology\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'org_reputation_packet',
    variant_id: 'org_reputation_packet:v2',
    label: 'Regulatory / institutional uptake',
    criterion_map: ['h3_viii'],
    filename_keywords: [
      'regulatory-uptake', 'adoption', 'standards-cited', 'government-reference',
    ],
    content_signals: [
      /\b(adopted|implemented|incorporated|referenced)\b[^.\n]{0,80}\b(framework|standard|methodology|product)\b/i,
      /\b(regulation|regulatory\s+(notice|guidance)|agency\s+letter)\b/i,
    ],
    exclusion_signals: [],
  },
  {
    doc_type: 'org_reputation_packet',
    variant_id: 'org_reputation_packet:v3',
    label: 'Press about the organization + partnership evidence',
    criterion_map: ['h3_viii'],
    filename_keywords: [
      'org-press', 'partnership', 'funding-round', 'scale', 'kurumsal-haberler',
    ],
    content_signals: [
      /\b(Series\s+[A-E]|seed\s+round|funding\s+round|partnership|joint\s+venture)\b/i,
      /\b(employees|headcount)\b[^.\n]{0,40}\b\d{2,}\b/i,
      /\b(announces|partners\s+with|raises|closes)\b/i,
    ],
    exclusion_signals: [],
  },

  /* comparable_evidence_packet (1) ------------------------------------- */
  {
    doc_type: 'comparable_evidence_packet',
    variant_id: 'comparable_evidence_packet:v1',
    label: 'Comparable-evidence brief (8 CFR § 204.5(h)(4))',
    criterion_map: [
      'h3_i', 'h3_ii', 'h3_iii', 'h3_iv', 'h3_v', 'h3_vi',
      'h3_vii', 'h3_viii', 'h3_ix', 'h3_x',
    ],
    filename_keywords: [
      'comparable-evidence', 'h4-brief', '204-5-h-4', 'substitute-evidence',
    ],
    content_signals: [
      /\b8\s+CFR\s+§?\s*204\.5\s*\(\s*h\s*\)\s*\(\s*4\s*\)/i,
      /\bcomparable\s+evidence\b/i,
      /\bVisinscaia\b/i,
      /\bdoes\s+not\s+readily\s+apply\b/i,
    ],
    exclusion_signals: [],
  },
];

/**
 * Lookup map by variant_id. Built once at module load so the classifier
 * doesn't re-scan the array per call.
 */
export const EB1A_VARIANT_BY_ID: Readonly<
  Record<Eb1aVariantId, Eb1aVariant>
> = Object.freeze(
  Object.fromEntries(
    EB1A_VARIANT_MANIFEST.map((v) => [v.variant_id, v]),
  ) as Record<Eb1aVariantId, Eb1aVariant>,
);

/** Coarse criterion → human label, for UI / logging. */
export const HH3_CRITERION_LABELS: Readonly<Record<Hh3Criterion, string>> = {
  h3_i: 'Awards (h)(3)(i)',
  h3_ii: 'Membership (h)(3)(ii)',
  h3_iii: 'Media (h)(3)(iii)',
  h3_iv: 'Judge (h)(3)(iv)',
  h3_v: 'Original Contributions (h)(3)(v)',
  h3_vi: 'Authorship (h)(3)(vi)',
  h3_vii: 'Display (h)(3)(vii)',
  h3_viii: 'Critical Role (h)(3)(viii)',
  h3_ix: 'Remuneration (h)(3)(ix)',
  h3_x: 'Commercial Success (h)(3)(x)',
};
